# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

# refer the repository where docker file is kept
resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cb2d395a-6cf3-43a8-9a6d-31bd966eb574'
  imageRepository: 'sqlapp'
  containerRegistry: 'localregistryaruna124.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/WebApp/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: PowerShell@2
      displayName: 'List contents of Artifact Staging Directory'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Listing contents of $(Build.SourcesDirectory):"
          Get-ChildItem -Path $(Build.SourcesDirectory)\*.* -Recurse -Force | Out-String -Width 180
          
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: false
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    

    - task: PowerShell@2
      displayName: 'List contents of Artifact Staging Directory'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Listing contents of $(Build.ArtifactStagingDirectory):"
          Get-ChildItem -Path $(Build.ArtifactStagingDirectory)\*.* -Recurse -Force | Out-String -Width 180
          
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        buildContext: '$(Build.ArtifactStagingDirectory)/WebApp'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
